### ISSUE TITLE
Package a .deb

### ISSUE THREAD

**Issue by mvisonneau** [sevagh/goat#42]
it could be nice to have a .deb package as well

**Comment by sevagh** [comment]
I think the better idea is to remove the RPM, since this is just a Go binary that can run anywhere.

**Comment by sevagh** [comment]
I'll package zipped binaries instead.

**Comment by sevagh** [comment]
Upon further consideration, the systemd unit is useful. I will look at https://fpm.readthedocs.io/en/latest/ and add you as a reviewer to my branch with the new documentation + deb file.

**Comment by mvisonneau** [comment]
Agreed, I have a systemd unit as well for my debian deployments which makes it useful/easier to manage

**Comment by sevagh** [comment]
What do you think of the parametrized systemd unit (i.e. `goat@ebs`, `goat@eni`) - is that irritating?

**Comment by sevagh** [comment]
Deb here: https://github.com/sevagh/goat/releases/tag/1.0.0

**Comment by sevagh** [comment]
I improved the deb packaging and it's now generated from the Dockerfile.build
