### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by bilco105** [sevagh/goat#49]
Hi @sevagh 

First of all, really appreciate the work you've put into this tool - we use it a lot.

Recently though, I've randomly started encountering a problem that I've not seen before, specifically this error:

```
INFO[0000] Running goat for ebs
INFO[0000] WELCOME TO GOAT
INFO[0000] 1: COLLECTING EC2 INFO
INFO[0000] Establishing metadata client
INFO[0000] Retrieved metadata successfully               instance_id=i-0a403f852293bd8e3
INFO[0000] Using metadata to initialize EC2 SDK client   az=eu-west-1a instance_id=i-0a403f852293bd8e3 region=eu-west-1
INFO[0000] 2: COLLECTING EBS INFO
INFO[0000] Searching for EBS volumes
INFO[0000] Classifying EBS volumes based on tags
INFO[0000] 3: ATTACHING EBS VOLS
INFO[0000] 4: MOUNTING ATTACHED VOLS
panic: runtime error: index out of range

goroutine 1 [running]:
main.prepAndMountDrives(0xc0004388e0, 0x5, 0xab95d0, 0x0, 0x0)
	/home/shanssian/go/src/github.com/sevagh/goat/ebs.go:42 +0x1350
main.GoatEbs(0x7d1b00, 0x7cd503, 0x7)
	/home/shanssian/go/src/github.com/sevagh/goat/ebs.go:35 +0x256
main.main()
	/home/shanssian/go/src/github.com/sevagh/goat/main.go:66 +0x4c
```

The EBS volumes attach fine, however, they fail to mount. This looked the same as #47 initially, however, I've upgraded to 1.0.2 and the error persists.

The tagging all appears to be correct, GOAT-IN:FsType, GOAT-IN:MountPath, GOAT-IN:NodeId, GOAT-IN:Prefix, & GOAT-IN:VolumeName are all set, and I've verified the IAM permissionns are correct.

Any ideas?

**Comment by sevagh** [comment]
I'm glad the tool has been useful.

The problem could be some sort of flakiness in the AWS API, and I believe my code is sloppy around checking for empty arrays.

Also, it could be that the disks are somehow already attached, in which case my code ignores them - I believe that's a corner case that I hadn't thought through, I could proceed to the next steps (Mount, etc.) even if the disks are already attached.

How do you create EC2 machines + EBS vols? Terraform?

Do you have an example of a log from a successful run stored somewhere? I believe the emptiness between steps 2-3 and 3-4 could indicate the "disks already attached therefore my code doesn't add them to the array of disks to mount" hypothesis.

**Comment by bilco105** [comment]
Thanks for the speedy response.

I've just downgraded to 0.6.0 which seems to have got things working again. 

That's certainly quite possible. Goat is running at boot, so it may well have failed to mount because of some other reason, after having already attached all the volumes, then died.

I'm then running `goat ebs` a second time, which is where I'm seeing the error above.

I'll try upgrading back to 1.0.2 shortly and running it with no volumes attached to see what happens there. Sounds like I'm potentially running into two different issues

**Comment by bilco105** [comment]
Ok, with everything detached, I get a different problem

```FATA[0020] Drive /dev/xvdl doesn't exist after attaching - checked with stat 10 times  vol_id=vol-0c17eb2e0d145df15 vol_name=export
```

Interestingly, that volume took longer to attach than goat was willing to wait.

**Comment by sevagh** [comment]
Can you test this hotfix? https://github.com/sevagh/goat/releases/tag/1.0.3-rc0

**Comment by bilco105** [comment]
@sevagh That appears to have resolved the original issue 👍 

I'm now getting this:
```
FATA[0000] Couldn't mount: no such device                vol_name=archive vols="[{vol-06ca06283f3290a4e archive -1 1 /dev/xvdb /var/www/html/akeneo/app/archive ext4}]"
```

We're using nvme, which is probably why - it should be `/dev/nvme1n1`

**Comment by sevagh** [comment]
I _should_ be getting that attached device name from the AWS API: https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#VolumeAttachment

**Comment by bilco105** [comment]
@sevagh Do you want me to raise a new issue for the above? then you can close this one off

**Comment by sevagh** [comment]
This same issue is OK. I'll get back to you soon.

**Comment by sevagh** [comment]
Can you print the logs surrounding the above error message? There are some additional functions related to nvme (which another user helped contribute) - I'm not very well versed in Nitro and nvme devices.

**Comment by bilco105** [comment]
Sure, here you go:

```
INFO[0000] Running goat for EBS
INFO[0000] WELCOME TO GOAT
INFO[0000] 1: COLLECTING EC2 INFO
INFO[0000] Establishing metadata client
INFO[0000] Retrieved metadata successfully               instance_id=xxx
INFO[0000] Using metadata to initialize EC2 SDK client   az=eu-west-1a instance_id=xxx region=eu-west-1
INFO[0000] 2: COLLECTING EBS INFO
INFO[0000] Searching for EBS volumes
INFO[0000] Classifying EBS volumes based on tags
INFO[0000] 3: ATTACHING EBS VOLS
INFO[0000] Volume is unattached, picking drive name      vol_id=xxx vol_name=filestorage
INFO[0000] Executing AWS SDK attach command              vol_id=xxx vol_name=filestorage
INFO[0000] {
  AttachTime: 2019-08-11 10:33:47.727 +0000 UTC,
  Device: "/dev/xvdb",
  InstanceId: "xxx",
  State: "attaching",
  VolumeId: "xxx"
}  vol_id=xxx vol_name=filestorage
FATA[0020] Drive /dev/xvdb doesn't exist after attaching - checked with stat 10 times  vol_id=xxx vol_name=filestorage
```

The issue with nvme volumes is that the attachment info shows as `/dev/xvdb`, but presents as `/dev/nvme1n1`. 

The volume ID is embedded in the serial for the device identification, so that might be the easiest way of determining it, but would require having the utility installed:

```
[root@ip-10-11-16-200 ~]# nvme list
Node             SN                   Model                                    Namespace Usage                      Format           FW Rev
---------------- -------------------- ---------------------------------------- --------- -------------------------- ---------------- --------
/dev/nvme0n1     volxxx Amazon Elastic Block Store               1           0.00   B /  17.18  GB    512   B +  0 B   1.0
/dev/nvme1n1     volxxx Amazon Elastic Block Store               1           0.00   B /   4.84  TB    512   B +  0 B   1.0
[root@ip-10-11-16-200 ~]#
```

**Comment by bilco105** [comment]
Actually, looking at the code, there is already some nvme logic using go-ebsnvme - which seems to try and find the correct nvme device using the devicename. 

Potentially better sticking with that, as it doesn't require an external package (nvme-cli).

As far as I can see, the issue is here: https://github.com/sevagh/goat/blob/b6af4b2b37cc6867d154aa19716e1667146b98cc/filesystem/drive.go#L49

It should be returning `device`, not `name`.

**Comment by bilco105** [comment]
Just had a quick look and have a feeling that the issue is potentially here:

https://github.com/sevagh/goat/blob/81f1aa344dc93f16d16f9682cd3aff04a0842992/ebs.go#L52-L53

Basically, the logic to determine the nvme device name is skipped over completely when the device already has a label, which will always be the case on the second mounting attempt

**Comment by sevagh** [comment]
Nice sleuthing - it looks like I should put a call to this function, GetActualBlockDeviceName, somewhere: https://github.com/sevagh/goat/blob/b6af4b2b37cc6867d154aa19716e1667146b98cc/filesystem/drive.go#L38

Maybe when writing the fstab entry - but I'm having trouble discovering where the link between the label and nvme device name exists.

**Comment by sevagh** [comment]
I'm building a 1.0.3-rc1

**Comment by sevagh** [comment]
https://github.com/sevagh/goat/releases/tag/1.0.3-rc1

The gist is that I put the "GetActualBlockDeviceName" call early in the code to have the real nvme name in the volume struct rather than substituting it in the future.

**Comment by sevagh** [comment]
What's funny is that I think all of this workaround comes from me choosing `/dev/xvd{b,c,d,e,f,g,...}` as a random device name for both non-NVME and NVME devices. So this "rediscovery" of `/dev/nvme01` from `/dev/xvdb` is correcting a mistaken initial assumption in my code. But it's a bit entrenched and for now I want your bug to be solved.

**Comment by bilco105** [comment]
Made some progress, it's now failing to mount, but using the correct device name:

```
FATA[0000] Couldn't mount: no such device                vol_name=media vols="[{vol-000000000 media -1 1 /dev/nvme4n1 /var/www/html ext4}]"
```

**Comment by sevagh** [comment]
If you run `ls -l /dev/disk/by-label`, perhaps the old LABEL still points to the bad name.

**Comment by bilco105** [comment]
Nope, they all point to the correct nvme devices

**Comment by sevagh** [comment]
I might have found a leftover place where I don't correct the AttachedName for nvme. Hold tight for rc2...

**Comment by sevagh** [comment]
https://github.com/sevagh/goat/releases/tag/1.0.3-rc2

I'm cutting rcs frequently since it's a safe way for us to share trusted binaries (vs me emailing you a binary).

**Comment by bilco105** [comment]
Yeah, no worries.

Same error, although interestingly, it has now managed to mount two volumes before bombing out.

It's only put one of the above volumes into /etc/fstab as well

**Comment by bilco105** [comment]
Also, as a side note, it bombs out if something is already mounted, even though potentially it was Goat that mounted it in the first place (i.e. on a second run).

Feels like it should just break out of the loop for that paticular volume, rather than exiting completely. 

Admitadly I guess it being run multiple times (as opposed to just at boot) wasn't an originally intended use-case

**Comment by sevagh** [comment]
Idempotence is a good goal to have - it's strange for a tool to panic because of something it did a few minutes ago.

Unfortunately I don't use AWS (and haven't, since writing this tool) so I can't easily iterate over code to solve this issue.

**Comment by bilco105** [comment]
I'll have a play locally and see if I can get it working, then submit a PR back

**Comment by bilco105** [comment]
Submitted a PR for this. Not ideal, but it works.

FWIW, we're fairly heavy users of Goat, and an AWS consultancy. We'd be happy to take over maintenance if you're not using AWS at your current place.

**Comment by sevagh** [comment]
Thanks for PR - re: taking over, that's a good idea. What's the best way to denote the change? Perhaps a note in the description that https://github.com/steamhaus/goat is official?

![descr](https://user-images.githubusercontent.com/8574092/62862855-1fdace00-bcd5-11e9-89d4-a5f5eb15c6d2.png)

And I could archive this one.

**Comment by bilco105** [comment]
Sure.

I'm pretty sure within the repo settings, there's a 'transfer' option. That then keeps a redirect in place from segagh/goat to steamhaus/goat.

I'd need to get rid of the fork first though

**Comment by bilco105** [comment]
I've removed the fork, so feel free to do the transfer if you'd like

**Comment by sevagh** [comment]
I'd prefer not to do a transfer. Would you be OK with continuing main development on your fork? Like I said, I'll point to it from this repo.

**Comment by bilco105** [comment]
Sure, can do that if you'd prefer. Will fork it again later this evening

**Comment by sevagh** [comment]
Thanks @bilco105 - I'll go ahead and archive goat for now. If you have any questions about the build process, etc. let me know (but `make docker_build` should build all the artifacts and put it in `./pkg`).
